// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class Leaderboard
{
        public const string achievement_finishat_stage1 = "CgkI0u_Xu48EEAIQCg"; // <GPGSID>
        public const string leaderboard_stage01 = "CgkI0u_Xu48EEAIQAQ"; // <GPGSID>
        public const string leaderboard_stage02 = "CgkI0u_Xu48EEAIQAg"; // <GPGSID>
        public const string leaderboard_stage03 = "CgkI0u_Xu48EEAIQAw"; // <GPGSID>
        public const string achievement_upto50kat_stage1 = "CgkI0u_Xu48EEAIQBA"; // <GPGSID>
        public const string achievement_upto50kat_stage2 = "CgkI0u_Xu48EEAIQBQ"; // <GPGSID>
        public const string achievement_upto50kat_stage3 = "CgkI0u_Xu48EEAIQBg"; // <GPGSID>
        public const string achievement_upto100kat_stage1 = "CgkI0u_Xu48EEAIQBw"; // <GPGSID>
        public const string achievement_upto100kat_stage2 = "CgkI0u_Xu48EEAIQCA"; // <GPGSID>
        public const string achievement_upto100kat_stage3 = "CgkI0u_Xu48EEAIQCQ"; // <GPGSID>
        public const string achievement_finishat_stage2 = "CgkI0u_Xu48EEAIQCw"; // <GPGSID>
        public const string achievement_finishat_stage3 = "CgkI0u_Xu48EEAIQDA"; // <GPGSID>
        public const string achievement_thank_you_for_playing = "CgkI0u_Xu48EEAIQDQ"; // <GPGSID>

}

